### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by xhackax47** [RadouaneGaroiaz/ui-announcement#1]
**Describe the issue**

Hello, ive a big problem when i try to rebuild the project (ive installed yarn, typescript and react)
`$ yarn build
yarn run v1.22.22
$ tsc && vite build
src/components/App.tsx(1,44): error TS2307: Cannot find module 'react' or its corresponding type declarations.
src/components/App.tsx(51,54): error TS7031: Binding element 'type' implicitly has an 'any' type.
src/components/App.tsx(51,60): error TS7031: Binding element 'message' implicitly has an 'any' type.
src/components/App.tsx(51,69): error TS7031: Binding element 'speed' implicitly has an 'any' type.
src/components/App.tsx(56,20): error TS7006: Parameter 'prevPosition' implicitly has an 'any' type.
src/components/App.tsx(71,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(71,5): error TS2307: Cannot find module 'react/jsx-runtime' or its corresponding type declarations.
src/components/App.tsx(87,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(98,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(99,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(109,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(110,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(131,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/components/App.tsx(140,5): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/hooks/useNuiEvent.ts(1,53): error TS2307: Cannot find module 'react' or its corresponding type declarations.
src/main.tsx(1,19): error TS2307: Cannot find module 'react' or its corresponding type declarations.
src/main.tsx(2,22): error TS2307: Cannot find module 'react-dom/client' or its corresponding type declarations.
src/main.tsx(8,3): error TS2307: Cannot find module 'react/jsx-runtime' or its corresponding type declarations.
src/providers/VisibilityProvider.tsx(7,8): error TS2307: Cannot find module 'react' or its corresponding type declarations.
src/providers/VisibilityProvider.tsx(22,3): error TS7031: Binding element 'children' implicitly has an 'any' type.
src/providers/VisibilityProvider.tsx(46,5): error TS2307: Cannot find module 'react/jsx-runtime' or its corresponding type declarations.
src/providers/VisibilityProvider.tsx(52,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/providers/VisibilityProvider.tsx(56,7): error TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
src/utils/debugData.ts(16,19): error TS2339: Property 'env' does not exist on type 'ImportMeta'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
**Expected behavior**

Build OK

**To Reproduce**

Try a build at local environment.

**Media**

![image](https://github.com/user-attachments/assets/c085991c-55a4-4343-be36-f2e34bb4daf9)

**Additional context**

**Comment by xhackax47** [comment]
To fix this error, install the types and rebuild

![image](https://github.com/user-attachments/assets/7f9c4469-f921-4811-8c10-767d0835ffa8)

**Comment by RadouaneGaroiaz** [comment]
you need to run command (yarn) to install depandencies befor the build command
